# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "voicecom_sms"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Evgenia Manolova"]
  s.date = "2013-04-08"
  s.description = "A fast SMS engine that uses VoiceCom as a service provider"
  s.email = "emanolova@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/voicecom_sms.rb",
    "lib/voicecom_sms/generators/voicecom_sms/install/install_generator.rb",
    "lib/voicecom_sms/message.rb",
    "lib/voicecom_sms/provider.rb",
    "lib/voicecom_sms/provider/request.rb",
    "lib/voicecom_sms/provider/response.rb",
    "lib/voicecom_sms/recipient.rb",
    "lib/voicecom_sms/verification_code.rb",
    "spec/spec_helper.rb",
    "spec/voicecom_sms/request_spec.rb",
    "spec/voicecom_sms_spec.rb"
  ]
  s.homepage = "http://github.com/zzeni/voicecom_sms"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ruby interface to the VoiceCom SMS Gateway API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.2.0"])
      s.add_runtime_dependency(%q<faraday>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<activerecord>, ["~> 3.2.0"])
      s.add_dependency(%q<faraday>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.3.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 3.2.0"])
    s.add_dependency(%q<faraday>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.3.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

