# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "voicecom_sms"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Empower United Services", "Evgenia Manolova"]
  s.date = "2013-04-11"
  s.description = "A fast SMS engine that uses VoiceCom as a service provider"
  s.email = "rado@empowerunited.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/generators/templates/initializers/voicecom_sms.rb",
    "lib/generators/templates/migrations/create_voicecom_messages.rb",
    "lib/generators/voicecom_sms_generator.rb",
    "lib/voicecom_sms.rb",
    "lib/voicecom_sms/message.rb",
    "lib/voicecom_sms/provider.rb",
    "lib/voicecom_sms/request.rb",
    "lib/voicecom_sms/response.rb",
    "spec/spec_helper.rb",
    "spec/voicecom_sms/provider_spec.rb",
    "voicecom_sms.gemspec"
  ]
  s.homepage = "http://github.com/empowerunited/voicecom_sms"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ruby interface to the VoiceCom SMS Gateway API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.2.0"])
      s.add_runtime_dependency(%q<hashie>, ["~> 1.2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<sqlite3>, ["~> 1.3.6"])
      s.add_development_dependency(%q<database_cleaner>, ["~> 0.9.1"])
    else
      s.add_dependency(%q<activerecord>, ["~> 3.2.0"])
      s.add_dependency(%q<hashie>, ["~> 1.2.0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.3.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<sqlite3>, ["~> 1.3.6"])
      s.add_dependency(%q<database_cleaner>, ["~> 0.9.1"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 3.2.0"])
    s.add_dependency(%q<hashie>, ["~> 1.2.0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.3.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<sqlite3>, ["~> 1.3.6"])
    s.add_dependency(%q<database_cleaner>, ["~> 0.9.1"])
  end
end

